site_name: ERP Documentation

docs_dir: docs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material

nav:
  - Overview: ERP_Product_Overview.md
  - Architecture: ERP_Architecture.md
  - Technology Stack: Technology_Stack_Overview_and_Justification.md
  - Sujith:
      - ERP Architecture: sujith/erp_architecture_v1.md
  - Resil:
      - Introduction: resil/initial.md
      - ERP Signup Flow: resil/erp_signup_flow.md
      - ERP Signup Wireframes: resil/erp_signup_wireframes.md
      - ERP Google Auth Signup: resil/erp_google_auth_signup.md
  - Dhamodhar:
      - Introduction: dhamodhar/initial.md

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
